<?php 
 return  array (
  'shop_title' => '挺好121听 11212阿萨为商城',
  'shop_keyword' => '韩国海购,尤为商城',
  'shop_desc' => '尤为商城为韩国海外直购，实时跟踪明星的小物件',
  'shop_mark' => '\\public\\templates',
  'shop_uploads' => '\\public\\Uploads',
  'shop_copyright' => '黎宝宝  版权所有',
  'shop_number' => '3135131',
  'stats_code' => '切切胜多负少的',
  'access_ip' => '',
  'max_num' => '',
  'send_mode' => 'smtp',
  'smtp_server' => 'smtp.163.com',
  'smtp_port' => '25',
  'smtp_user' => 'nietzsche_nc@163.com',
  'smtp_pwd' => 'li6565697',
  'test_eamil' => 'nietzsche_nc@163.com',
  'open' => '0',
);